list( APPEND SERVER_INCLUDES
    ${CMAKE_CURRENT_LIST_DIR}/
    ${CMAKE_CURRENT_LIST_DIR}/database
    ${CMAKE_CURRENT_LIST_DIR}/sha256/
    ${CMAKE_CURRENT_LIST_DIR}/server/
)

list( APPEND SERVER_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/
    ${CMAKE_CURRENT_LIST_DIR}/database/database.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sha256/sha256.cpp
    ${CMAKE_CURRENT_LIST_DIR}/server/server.cpp
)